DUKE = "duke"
CONTESSA = "contessa"
ASSASSIN = "assassin"
CAPTAIN = "captain"
INQUISITOR = "inquisitor"

INCOME = "income"
FOREIGN_AID = "foreign_aid"
COLLECT_TAXES = "collect_taxes"
ASSASSINATE = "assassinate"
EXTORTION = "extortion"
INVESTIGATE = "investigate"
EXCHANGE = "exchange"
COUP = "coup"